### ISSUE TITLE
Umbrella issue for Warehouse demo

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#57]
#### Purpose of the demo

Demonstrate full workflow of the **[Starcounter hosts everything](https://starcounter.gitbooks.io/rebelslounge/content/warehouse/warehouse_solutions.html)** solution.

- [x] Develop Warehouse.
- [x] Develop WarehouseClient.
- [x] Develop PlaygroundKeeper.
- [x] Integrate Warehouse with Launcher.
- [x] Integrate WarehouseClient with Launcher.
- [x] Integrate Warehouse, WarehouseClient, PlaygroundKeeper, SignIn, Register apps all together.
- [x] Setup physical machines: Warehouse.
- [x] Setup physical machines: WarehouseClient.
- [x] Setup physical machines: Playgrounds.
- [x] Perform full test using the physical machines.

Additional features

- [ ] Implement nice UI for the solution.
- [ ] Implement `<warehouse-client-widget>` to integrate WarehouseClient into a website.

cc @andwah, @malx122, @dan31

**Comment by miyconst** [comment]
#### Demo description and steps

**Customer (application vendor) side**

1. Go to `warehouse.mysampleapp.com`.
2. Register a new user. Let's assume the user will be **Tunity**.
3. Create a new Organization - **Tunity AB**.
4. Upload multiple application packages - **Tunity CRM**, **Tunity Calendar**.
5. Create a new Store - **Tunity Store**.
6. Add all applications to the Store.
7. Save all the changes.
8. Install own WarehouseClient - `tunity.mysampleapp.com`.
9. Open `tunity.mysampleapp.com` and setup connection with **Tunity Store**.
10. Open `tunity.mysampleapp.com` as an anonymous user and make sure that all applications are listed.

**Client (application vendor's customer) side**

1. Go to `tunity.mysampleapp.com`.
2. Read information about listed applications.
3. Choose an interesting application.
4. Click **Try** button.
5. Register with a new account - **Tester**.
6. Observe hive creating and app installation progress.
7. Open `tester.mysampleapp.com`.
8. Test the installed app.
9. Navigate back to `tunity.mysampleapp.com`.
10. Install rest of the apps.
11. Navigate to `tester.mysampleapp.com` once again.
12. Test all of the apps together.

**Comment by miyconst** [comment]
The demo went well. Closing the issue.
